// Generated by Selenium IDE
/*
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCPROD02Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCPROD02() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1513, 833));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-button\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-sidebar-link\"]")).click();
    driver.findElement(By.id("react-burger-cross-btn")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"about-sidebar-link\"]")).click();
    driver.findElement(By.id("transcend-consent-manager")).click();
    driver.findElement(By.id("transcend-consent-manager")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"logout-sidebar-link\"]")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"login-button\"]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"secondary-header\"]")).click();
    driver.findElement(By.id("react-burger-cross-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"reset-sidebar-link\"]")).click();
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"remove-sauce-labs-bike-light\"]")).getText(), is("Remove"));
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).getText(), is("Remove"));
    driver.findElement(By.id("react-burger-cross-btn")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"inventory-sidebar-link\"]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"about-sidebar-link\"]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"logout-sidebar-link\"]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"reset-sidebar-link\"]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("*[data-test=\"about-sidebar-link\"]")).click();
    assertThat(driver.getTitle(), is("Sauce Labs: Cross Browser Testing, Selenium Testing & Mobile Testing"));
    {
      WebElement element = driver.findElement(By.linkText("Learn More"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
*/