// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCPROD032Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCPROD032() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1513, 835));
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".error-message-container")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]")).getText(), is("Add to cart"));
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
  }
}
