// Generated by Selenium IDE
/*
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCPROD033Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCPROD033() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1303, 692));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector(".inventory_item:nth-child(2) > .inventory_item_description")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).getText(), is("Sauce Labs Backpack"));
    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).getText(), is("Sauce Labs Backpack"));
    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    assertThat(driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).getText(), is("Sauce Labs Bike Light"));
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    assertThat(driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).getText(), is("Sauce Labs Bolt T-Shirt"));
    driver.findElement(By.cssSelector("#item_5_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    assertThat(driver.findElement(By.cssSelector("#item_5_title_link > .inventory_item_name")).getText(), is("Sauce Labs Fleece Jacket"));
    driver.findElement(By.cssSelector("#item_2_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    assertThat(driver.findElement(By.cssSelector("#item_2_title_link > .inventory_item_name")).getText(), is("Sauce Labs Onesie"));
    assertThat(driver.findElement(By.cssSelector("#item_3_title_link > .inventory_item_name")).getText(), is("Test.allTheThings() T-Shirt (Red)"));
    assertThat(driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).getText(), is("Sauce Labs Bike Light"));
    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_5_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_2_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"secondary-header\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_3_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
  }
}
*/